(()=>{'use strict';
/* Aetheria live-data layer r20260917-2 */
const ATTR=['gorgeous','simple','elegant','lively','mature','cute','sexy','pure','warm','cool'];
const LABEL={gorgeous:'Quý phái',simple:'Đơn giản',elegant:'Thanh lịch',lively:'Năng động',mature:'Trưởng thành',cute:'Dễ thương',sexy:'Gợi cảm',pure:'Trong sáng',warm:'Giữ ấm',cool:'Mát mẻ'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cat=x=>String(x.category||x.typeName||x.type||'Chưa phân loại');
let ITEMS=[],STAGES=[];
function attrs(s){return s?.attrs||s?.attributes||{}}
function score(x,s){return ATTR.reduce((n,k)=>n+(+x[k]||0)*(+attrs(s)[k]||0),0)}
function stage(){return STAGES.find(s=>String(s.id)==String(document.querySelector('#rankStageSelect')?.value))}
function style(){if(document.querySelector('#aetheriaLiveStyle'))return;const s=document.createElement('style');s.id='aetheriaLiveStyle';s.textContent=`.aetheria-slot-panel{margin:0 0 18px;padding:16px 18px;border:1px solid rgba(142,98,93,.16);border-radius:18px;background:rgba(255,250,245,.72);box-shadow:0 10px 30px rgba(100,60,50,.06)}.aetheria-slot-head{display:flex;gap:14px;align-items:center;justify-content:space-between;flex-wrap:wrap}.aetheria-slot-head>b,.aetheria-slot-head>div:first-child b{display:block;font-family:'Playfair Display',serif;font-size:17px;color:#714b4b}.aetheria-slot-head small{display:block;margin-top:3px;color:#92736d}.aetheria-slot-tabs{display:flex;gap:7px;overflow:auto;max-width:100%;padding-bottom:3px}.aetheria-slot-tabs button{white-space:nowrap;border:1px solid rgba(142,98,93,.16);background:#fffaf6;color:#765957;border-radius:999px;padding:7px 11px;cursor:pointer}.aetheria-slot-tabs button.active{background:#8d5b68;color:#fff;border-color:#8d5b68}.aetheria-data-note{margin:10px 0 18px;padding:10px 13px;border-left:3px solid #b88972;color:#806662;background:rgba(255,247,240,.7);font-size:12px;line-height:1.55}.aetheria-data-note:before{content:'✦ ';color:#b88972}@media(max-width:640px){.aetheria-slot-panel{padding:13px}.aetheria-slot-head{display:block}.aetheria-slot-tabs{margin-top:10px}.aetheria-slot-tabs button{font-size:11px;padding:6px 9px}}`;document.head.appendChild(s)}
function enhanceInfo(s){const old=document.querySelector('#rankDescription');if(!old||!s)return;const tags=Array.isArray(s.tags)?s.tags:[],w=ATTR.map(k=>[k,+attrs(s)[k]||0]).filter(x=>x[1]).sort((a,b)=>b[1]-a[1]);old.innerHTML=`<b>${esc(s.label||s.name||s.id)}</b> · ${w.slice(0,2).map(x=>LABEL[x[0]]).join(' + ')||'chưa có trọng số'}${tags.length?` · Tag: ${tags.map(esc).join(' · ')}`:''}<br><small>Top theo trọng số thuộc tính của đúng chặng/theme; đây là chỉ số tham khảo, không phải điểm trận đấu.</small>`}
function slotRank(){const s=stage(),root=document.querySelector('#rankingGrid');if(!s||!root)return;const limit=+(document.querySelector('#rankLimit')?.value||20),selected=document.querySelector('#rankCategory')?.value||'all';let rows=ITEMS.filter(x=>ATTR.some(k=>(+x[k]||0)>0)&&(selected==='all'||cat(x)===selected)).map(x=>({...x,__score:score(x,s)})).filter(x=>x.__score>0).sort((a,b)=>b.__score-a.__score||(+b.rarity||0)-(+a.rarity||0));const cats=[...new Set(rows.map(cat))].filter(Boolean).sort((a,b)=>a.localeCompare(b,'vi'));let panel=document.querySelector('#aetheriaSlotPanel');if(!panel){panel=document.createElement('div');panel.id='aetheriaSlotPanel';panel.className='aetheria-slot-panel';root.parentNode.insertBefore(panel,root)}const active=panel.dataset.active||'all';panel.innerHTML=`<div class="aetheria-slot-head"><div><b>Top theo từng loại đồ</b><small>${esc(s.label||s.name||s.id)}</small></div><div class="aetheria-slot-tabs"><button data-slot="all" class="${active==='all'?'active':''}">Tổng hợp</button>${cats.slice(0,18).map(c=>`<button data-slot="${esc(c)}" class="${active===c?'active':''}">${esc(c)}</button>`).join('')}</div></div>`;panel.querySelectorAll('button').forEach(b=>b.onclick=()=>{panel.dataset.active=b.dataset.slot;slotRank()});let view=active==='all'?rows:rows.filter(x=>cat(x)===active);root.innerHTML=view.slice(0,limit).map((x,i)=>`<article class="item-card rank-card" data-item-id="${esc(x.id)}"><div class="item-img"><img loading="lazy" src="${esc(x.image||'')}" alt="${esc(x.name)}" onerror="this.style.opacity=.25"><div class="rank-no">#${i+1}</div></div><div class="item-body"><div class="rank-name">${esc(x.name||'Chưa đặt tên')}</div><div class="meta">${esc(cat(x))}${x.suit?' • '+esc(x.suit):''}</div><div class="item-meta"><span class="score">${x.__score.toLocaleString('vi-VN',{maximumFractionDigits:1})} phù hợp</span></div></div></article>`).join('')||'<div class="empty">Không có item phù hợp.</div>';enhanceInfo(s);const info=document.querySelector('#rankInfo');if(info)info.textContent=`${s.label||s.name||s.id} • ${view.length.toLocaleString('vi-VN')} item phù hợp • Top ${Math.min(limit,view.length)}`}
async function boot(){try{style();const[a,b,c]=await Promise.all([fetch('./data/items.json?live=20260917',{cache:'no-store'}),fetch('./data/stages.json?live=20260917',{cache:'no-store'}),fetch('./data/stages-extra.json?live=20260917',{cache:'no-store'})]);const p=await a.json(),q=await b.json();ITEMS=Array.isArray(p.items)?p.items:Array.isArray(p)?p:[];STAGES=Array.isArray(q.stages)?q.stages:[];if(c.ok){const z=await c.json(),seen=new Set(STAGES.map(x=>x.id));for(const x of(z.stages||[]))if(!seen.has(x.id))STAGES.push(x)}const d=document.querySelector('#rankDescription');if(d&&!document.querySelector('#aetheriaDataNote')){const n=document.createElement('div');n.id='aetheriaDataNote';n.className='aetheria-data-note';n.textContent=`Kho hiện có ${ITEMS.length.toLocaleString('vi-VN')} item. Dữ liệu cộng đồng mới chỉ được dùng làm đầu mối; trước khi vào BXH phải xác minh và ghi nguồn.`;d.insertAdjacentElement('afterend',n)}setTimeout(()=>{if(stage())slotRank()},350);['rankStageSelect','rankLimit','rankCategory'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',()=>setTimeout(slotRank,40)));document.querySelectorAll('#rankTabs button').forEach(b=>b.addEventListener('click',()=>setTimeout(slotRank,60)));document.querySelector('#rankChapterSelect')?.addEventListener('change',()=>setTimeout(slotRank,60))}catch(e){console.warn('[Aetheria live]',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
