(()=>{'use strict';
/* Aetheria live-data layer r20260917-3 — grade-aware reference ranking */
const ATTR=['gorgeous','simple','elegant','lively','mature','cute','sexy','pure','warm','cool'];
const LABEL={gorgeous:'Quý phái',simple:'Đơn giản',elegant:'Thanh lịch',lively:'Năng động',mature:'Trưởng thành',cute:'Dễ thương',sexy:'Gợi cảm',pure:'Trong sáng',warm:'Giữ ấm',cool:'Mát mẻ'};
const GRADE_SCORE={SS:7,S:6,A:5,B:4,C:3,D:2,E:1,'—':0,'-':0};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
const CATEGORY={hair:'Tóc',top:'Áo',bottom:'Quần',dress:'Váy liền',coat:'Áo khoác',socks:'Tất',shoes:'Giày',makeup:'Trang điểm',accessory:'Phụ kiện',head:'Phụ kiện tóc',necklace:'Vòng cổ',earring:'Khuyên tai',bracelet:'Vòng tay',hand:'Phụ kiện tay',waist:'Phụ kiện eo',special:'Phụ kiện đặc biệt'};
let ITEMS=[],STAGES=[],GRADES={};
function attrs(s){return s?.attrs||s?.attributes||{}}
function gradeOf(x,k){return GRADES[String(x.id)]?.grades?.[k]||'—'}
function numericScore(x,s){return ATTR.reduce((n,k)=>n+(+x[k]||0)*(+attrs(s)[k]||0),0)}
function gradeScore(x,s){return ATTR.reduce((n,k)=>n+(GRADE_SCORE[gradeOf(x,k)]||0)*(+attrs(s)[k]||0),0)}
function score(x,s){const n=numericScore(x,s);return n>0?{value:n,mode:'numeric'}:{value:gradeScore(x,s),mode:'grade'}}
function categoryLabel(x){const raw=String(x.category||x.typeName||x.type||'Chưa phân loại');const k=norm(raw);return CATEGORY[k]||raw}
function stage(){return STAGES.find(s=>String(s.id)==String(document.querySelector('#rankStageSelect')?.value))}
function style(){if(document.querySelector('#aetheriaLiveStyle'))return;const s=document.createElement('style');s.id='aetheriaLiveStyle';s.textContent=`.aetheria-slot-panel{margin:0 0 18px;padding:16px 18px;border:1px solid rgba(142,98,93,.16);border-radius:18px;background:rgba(255,250,245,.72);box-shadow:0 10px 30px rgba(100,60,50,.06)}.aetheria-slot-head{display:flex;gap:14px;align-items:center;justify-content:space-between;flex-wrap:wrap}.aetheria-slot-head>b,.aetheria-slot-head>div:first-child b{display:block;font-family:'Playfair Display',serif;font-size:17px;color:#714b4b}.aetheria-slot-head small{display:block;margin-top:3px;color:#92736d}.aetheria-slot-tabs{display:flex;gap:7px;overflow:auto;max-width:100%;padding-bottom:3px}.aetheria-slot-tabs button{white-space:nowrap;border:1px solid rgba(142,98,93,.16);background:#fffaf6;color:#765957;border-radius:999px;padding:7px 11px;cursor:pointer}.aetheria-slot-tabs button.active{background:#8d5b68;color:#fff;border-color:#8d5b68}.aetheria-data-note{margin:10px 0 18px;padding:10px 13px;border-left:3px solid #b88972;color:#806662;background:rgba(255,247,240,.7);font-size:12px;line-height:1.55}.aetheria-data-note:before{content:'✦ ';color:#b88972}.aetheria-rank-insight{margin:0 0 18px;padding:15px 17px;border-radius:18px;background:linear-gradient(135deg,rgba(255,249,244,.95),rgba(246,233,225,.72));border:1px solid rgba(170,125,106,.18);color:#735d5d}.aetheria-rank-insight strong{font-family:'Playfair Display',serif;color:#63484d}.aetheria-rank-insight .ins-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin-top:11px}.aetheria-rank-insight .ins-cell{padding:9px 10px;border-radius:12px;background:rgba(255,255,255,.52);border:1px solid rgba(170,125,106,.12)}.aetheria-rank-insight .ins-cell b{display:block;font-size:14px;color:#7f5660}.aetheria-rank-insight .ins-cell span{font-size:10px;color:#9b8583}.rank-card .rank-source{font-size:10px;color:#9b8583;margin-top:5px}.rank-card .score.grade-index{font-weight:700}.rank-card .grade-mini{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.rank-card .grade-mini span{font-size:10px;padding:3px 6px;border-radius:999px;background:#f4e8e1;color:#76595a}.rank-card .grade-mini b{color:#8d5b68}.aetheria-rank-foot{margin-top:10px;font-size:10px;color:#9a8581;line-height:1.5}@media(max-width:640px){.aetheria-slot-panel{padding:13px}.aetheria-slot-head{display:block}.aetheria-slot-tabs{margin-top:10px}.aetheria-slot-tabs button{font-size:11px;padding:6px 9px}.aetheria-rank-insight .ins-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}`;document.head.appendChild(s)}
function enhanceInfo(s,mode){const old=document.querySelector('#rankDescription');if(!old||!s)return;const tags=Array.isArray(s.tags)?s.tags:[],w=ATTR.map(k=>[k,+attrs(s)[k]||0]).filter(x=>x[1]).sort((a,b)=>b[1]-a[1]);old.innerHTML=`<b>${esc(s.label||s.name||s.id)}</b> · ${w.slice(0,2).map(x=>LABEL[x[0]]).join(' + ')||'chưa có trọng số'}${tags.length?` · Tag: ${tags.map(esc).join(' · ')}`:''}<br><small>${mode==='grade'?'Xếp hạng tham khảo đang dùng hạng chữ SS→E đã đối chiếu từ nguồn item Việt, kết hợp trọng số của chặng.':'Xếp hạng tham khảo đang dùng chỉ số số học đã có trong dữ liệu.'} Không gọi đây là điểm trận đấu VNG.</small>`}
function insight(s,rows,mode){let box=document.querySelector('#aetheriaRankInsight');if(!box){box=document.createElement('div');box.id='aetheriaRankInsight';box.className='aetheria-rank-insight';document.querySelector('#rankingGrid')?.parentNode.insertBefore(box,document.querySelector('#rankingGrid'))}const w=ATTR.map(k=>[k,+attrs(s)[k]||0]).filter(x=>x[1]).sort((a,b)=>b[1]-a[1]);const counts={};for(const x of rows)counts[categoryLabel(x)]=(counts[categoryLabel(x)]||0)+1;const cats=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,4);box.innerHTML=`<strong>✦ Phân tích nhanh cho chặng này</strong><div class="ins-grid"><div class="ins-cell"><b>${w.length}</b><span>thuộc tính có trọng số</span></div><div class="ins-cell"><b>${w.slice(0,1).map(x=>LABEL[x[0]]).join('')||'—'}</b><span>thuộc tính nổi bật</span></div><div class="ins-cell"><b>${rows.length.toLocaleString('vi-VN')}</b><span>item có dữ liệu để đối chiếu</span></div><div class="ins-cell"><b>${cats.map(x=>x[0]).join(' · ')||'—'}</b><span>nhóm đồ đang có dữ liệu</span></div></div><div class="aetheria-rank-foot">${mode==='grade'?'★ Hạng chữ là dữ liệu hiển thị từ nguồn công khai; Aetheria chỉ quy đổi thứ tự SS/S/A/B/C/D/E thành chỉ số tham khảo để sắp xếp, không biến nó thành chỉ số gốc.':'★ Chỉ số số học được lấy trực tiếp từ dữ liệu Aetheria khi trường đó có giá trị.'}</div>`}
function slotRank(){const s=stage(),root=document.querySelector('#rankingGrid');if(!s||!root)return;const limit=+(document.querySelector('#rankLimit')?.value||20),selected=document.querySelector('#rankCategory')?.value||'all';let base=ITEMS.filter(x=>selected==='all'||categoryLabel(x)===selected);let rows=base.map(x=>{const q=score(x,s);return {...x,__score:q.value,__mode:q.mode}}).filter(x=>x.__score>0).sort((a,b)=>b.__score-a.__score||(+b.rarity||0)-(+a.rarity||0)||String(a.name).localeCompare(String(b.name),'vi'));const cats=[...new Set(rows.map(categoryLabel))].filter(Boolean).sort((a,b)=>a.localeCompare(b,'vi'));let panel=document.querySelector('#aetheriaSlotPanel');if(!panel){panel=document.createElement('div');panel.id='aetheriaSlotPanel';panel.className='aetheria-slot-panel';root.parentNode.insertBefore(panel,root)}const active=panel.dataset.active||'all';panel.innerHTML=`<div class="aetheria-slot-head"><div><b>Top theo từng loại đồ</b><small>${esc(s.label||s.name||s.id)}</small></div><div class="aetheria-slot-tabs"><button data-slot="all" class="${active==='all'?'active':''}">Tổng hợp</button>${cats.slice(0,18).map(c=>`<button data-slot="${esc(c)}" class="${active===c?'active':''}">${esc(c)}</button>`).join('')}</div></div>`;panel.querySelectorAll('button').forEach(b=>b.onclick=()=>{panel.dataset.active=b.dataset.slot;slotRank()});let view=active==='all'?rows:rows.filter(x=>categoryLabel(x)===active);root.innerHTML=view.slice(0,limit).map((x,i)=>{const gr=ATTR.map(k=>[k,gradeOf(x,k)]).filter(a=>a[1]&&a[1]!=='—').sort((a,b)=>(GRADE_SCORE[b[1]]||0)-(GRADE_SCORE[a[1]]||0)).slice(0,3);return `<article class="item-card rank-card" data-item-id="${esc(x.id)}"><div class="item-img"><img loading="lazy" src="${esc(x.image||'')}" alt="${esc(x.name)}" onerror="this.style.opacity=.25"><div class="rank-no">#${i+1}</div></div><div class="item-body"><div class="rank-name">${esc(x.name||'Chưa đặt tên')}</div><div class="meta">${esc(categoryLabel(x))}${x.suit?' • '+esc(x.suit):''}</div><div class="item-meta"><span class="score ${x.__mode==='grade'?'grade-index':''}">${x.__score.toLocaleString('vi-VN',{maximumFractionDigits:1})} phù hợp</span></div>${gr.length?`<div class="grade-mini">${gr.map(g=>`<span><b>${g[1]}</b> ${LABEL[g[0]]}</span>`).join('')}</div>`:''}<div class="rank-source">${x.__mode==='grade'?'✦ Thuộc tính hạng chữ đã đối chiếu':'✦ Thuộc tính số đã có'}</div></div></article>`}).join('')||'<div class="empty">Không có item phù hợp.</div>';enhanceInfo(s,rows[0]?.__mode||'grade');insight(s,rows,rows[0]?.__mode||'grade');const info=document.querySelector('#rankInfo');if(info)info.textContent=`${s.label||s.name||s.id} • ${view.length.toLocaleString('vi-VN')} item phù hợp • Top ${Math.min(limit,view.length)}`}
function populateCats(){const sel=document.querySelector('#rankCategory');if(!sel)return;const current=sel.value;const cats=[...new Set(ITEMS.map(categoryLabel))].filter(Boolean).sort((a,b)=>a.localeCompare(b,'vi'));sel.innerHTML='<option value="all">Tất cả loại đồ</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if(cats.includes(current))sel.value=current}
async function boot(){try{style();const[a,b,c,d]=await Promise.all([fetch('./data/items.json?live=20260917r3',{cache:'no-store'}),fetch('./data/stages.json?live=20260917r3',{cache:'no-store'}),fetch('./data/stages-extra.json?live=20260917r3',{cache:'no-store'}),fetch('./data/item-attribute-grades.json?live=20260917r3',{cache:'no-store'})]);const p=await a.json(),q=await b.json();ITEMS=Array.isArray(p.items)?p.items:Array.isArray(p)?p:[];STAGES=Array.isArray(q.stages)?q.stages:[];if(c.ok){const z=await c.json(),seen=new Set(STAGES.map(x=>x.id));for(const x of(z.stages||[]))if(!seen.has(x.id))STAGES.push(x)}if(d.ok){const z=await d.json();GRADES=z.items||{};window.__aetheriaAttributeCoverage=z.coverage||{}}populateCats();const desc=document.querySelector('#rankDescription');if(desc&&!document.querySelector('#aetheriaDataNote')){const n=document.createElement('div');n.id='aetheriaDataNote';n.className='aetheria-data-note';n.textContent=`Kho hiện có ${ITEMS.length.toLocaleString('vi-VN')} item. Bảng xếp hạng tự chuyển sang dữ liệu hạng chữ khi chỉ số số chưa được điền; nguồn và trạng thái đối chiếu luôn được giữ.`;desc.insertAdjacentElement('afterend',n)}setTimeout(()=>{if(stage())slotRank()},350);['rankStageSelect','rankLimit','rankCategory'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',()=>setTimeout(slotRank,40)));document.querySelectorAll('#rankTabs button').forEach(b=>b.addEventListener('click',()=>setTimeout(slotRank,60)));document.querySelector('#rankChapterSelect')?.addEventListener('change',()=>setTimeout(slotRank,60))}catch(e){console.warn('[Aetheria live]',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
