(()=>{
'use strict';
const ATTRS=['gorgeous','simple','elegant','lively','mature','cute','sexy','pure','warm','cool'];
const LABEL={gorgeous:'Quý phái',simple:'Đơn giản',elegant:'Thanh lịch',lively:'Năng động',mature:'Trưởng thành',cute:'Dễ thương',sexy:'Gợi cảm',pure:'Trong sáng',warm:'Giữ ấm',cool:'Mát mẻ'};
const DATA='./data/items.json', STAGES='./data/stages.json', EXTRA='./data/stages-extra.json', SIZE=40;
let items=[],stages=[],filtered=[],page=1,group='aihoi',owned=[];try{owned=JSON.parse(localStorage.getItem('aetheria_wardrobe')||'[]')}catch(e){owned=[]}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fallback='data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="500" height="650"%3E%3Crect width="100%25" height="100%25" fill="%23f1e2dc"/%3E%3Ccircle cx="250" cy="210" r="85" fill="%23c58e9a"/%3E%3Cpath d="M100 560c20-160 90-220 150-220s130 60 150 220" fill="%23b96f7e"/%3E%3C/svg%3E';
const image=(u,n)=>`<img loading="lazy" decoding="async" src="${esc(u||fallback)}" alt="${esc(n||'Item')}" onerror="this.onerror=null;this.src='${fallback}'">`;
const cat=x=>String(x?.category||x?.typeName||x?.type||'Chưa phân loại').trim()||'Chưa phân loại';
const score=x=>ATTRS.reduce((n,k)=>n+(Number(x?.[k])||0),0);
const attrs=x=>ATTRS.map(k=>({k,v:Number(x?.[k])||0})).filter(a=>a.v).sort((a,b)=>b.v-a.v).slice(0,3);
const searchText=x=>[x.name,x.suit,x.source,x.category,x.type,x.typeName,x.style,Array.isArray(x.tags)?x.tags.join(' '):x.tags,...ATTRS.map(k=>LABEL[k])].join(' ').toLowerCase();
const stageScore=(x,s)=>ATTRS.reduce((n,k)=>n+(Number(x?.[k])||0)*(Number(s?.attrs?.[k])||0),0);
function notify(t){const e=$('#toast');if(e){e.textContent=t;e.classList.add('show');clearTimeout(window.__aToast);window.__aToast=setTimeout(()=>e.classList.remove('show'),1800)}}
function stars(n){n=Math.max(0,Math.min(5,Number(n)||0));return n?'★'.repeat(n)+'☆'.repeat(5-n):'—'}
function card(x,i,rank=false){const has=owned.some(v=>String(v)===String(x.id));const a=attrs(x).map(z=>`${LABEL[z.k]} ${z.v}`).join(' • ');const metric=rank?`${Number(x.__fit||0).toLocaleString('vi-VN',{maximumFractionDigits:1})} phù hợp`:score(x)?`${score(x).toLocaleString('vi-VN')} thuộc tính`:stars(x.rarity);return `<article class="item-card ${rank?'rank-card':''}" data-item-id="${esc(x.id)}"><div class="item-img">${image(x.image,x.name)}<button class="heart ${has?'on':''}" data-heart="${esc(x.id)}" aria-label="${has?'Bỏ khỏi tủ':'Thêm vào tủ'}">${has?'♥':'♡'}</button></div><div class="item-body">${rank?`<div class="rank-no">#${i+1}</div>`:''}<div class="rank-name">${esc(x.name||'Chưa đặt tên')}</div><div class="meta">${esc(cat(x))}${x.suit?` • ${esc(x.suit)}`:''}</div><div class="item-meta"><span class="rarity">${stars(x.rarity)}</span><span class="score">${metric}</span></div>${a?`<div class="attr-line">${esc(a)}</div>`:''}</div></article>`}
function stageChapter(s){const m=String(s.label||'').match(/Chương\s*[^•]+/i);return m?m[0].trim():'Khác'}
function currentStage(){return stages.find(s=>String(s.id)===String($('#rankStageSelect')?.value))}
function buildRankSelectors(){const chapter=$('#rankChapterSelect'),sel=$('#rankStageSelect');if(!chapter||!sel)return;const ss=stages.filter(s=>s.group===group);const ch=[...new Set(ss.map(stageChapter))];const oldC=chapter.value;chapter.innerHTML=ch.length?ch.map(c=>`<option>${esc(c)}</option>`).join(''):'<option>Chưa có dữ liệu</option>';if(ch.includes(oldC))chapter.value=oldC;const list=ss.filter(s=>stageChapter(s)===chapter.value);sel.innerHTML=list.length?list.map(s=>`<option value="${esc(s.id)}">${esc(s.label||s.name||s.id)}</option>`).join(''):'<option value="">Chưa có stage đã xác minh</option>';}
function renderRank(){const grid=$('#rankingGrid');if(!grid)return;buildRankSelectors();const s=currentStage();if(!s){grid.innerHTML='<div class="empty">Chưa có stage/theme đã xác minh cho nhóm này.</div>';return}let pool=items.filter(x=>score(x)>0);const c=$('#rankCategory')?.value||'all';if(c!=='all')pool=pool.filter(x=>cat(x)===c);pool=pool.map(x=>({...x,__fit:stageScore(x,s)})).filter(x=>x.__fit>0).sort((a,b)=>b.__fit-a.__fit||Number(b.rarity||0)-Number(a.rarity||0));const n=Number($('#rankLimit')?.value||20);grid.innerHTML=pool.slice(0,n).map((x,i)=>card(x,i,true)).join('')||'<div class="empty">Không có item phù hợp.</div>';const w=ATTRS.map(k=>[k,Number(s.attrs?.[k])||0]).filter(a=>a[1]).sort((a,b)=>b[1]-a[1]);if($('#rankInfo'))$('#rankInfo').textContent=`${s.label||s.name} • ${pool.length.toLocaleString('vi-VN')} item • ${w.slice(0,2).map(a=>LABEL[a[0]]).join(' + ')}`;if($('#rankDescription'))$('#rankDescription').textContent=`${s.name||s.label}. Chỉ số là độ phù hợp tham khảo theo trọng số của đúng chặng, không phải điểm trận đấu.`}
function filter(){const q=($('#wardrobeSearch')?.value||'').trim().toLowerCase(),c=$('#categoryFilter')?.value||'all',r=$('#rarityFilter')?.value||'all',o=$('#ownershipFilter')?.value||'all';filtered=items.filter(x=>{const h=owned.some(v=>String(v)===String(x.id));return(!q||searchText(x).includes(q))&&(c==='all'||cat(x)===c)&&(r==='all'||String(x.rarity||'')===r)&&(o==='all'||(o==='owned'&&h)||(o==='unowned'&&!h))});page=Math.min(page,Math.max(1,Math.ceil(filtered.length/SIZE)));renderLibrary()}
function renderLibrary(){const grid=$('#wardrobeGrid');if(!grid)return;const start=(page-1)*SIZE,rows=filtered.slice(start,start+SIZE),pages=Math.max(1,Math.ceil(filtered.length/SIZE));grid.innerHTML=rows.length?rows.map((x,i)=>card(x,start+i)).join(''):'<div class="empty">Không tìm thấy item.</div>';if($('#pageInfo'))$('#pageInfo').textContent=`Trang ${page} / ${pages}`;if($('#prevPage'))$('#prevPage').disabled=page<=1;if($('#nextPage'))$('#nextPage').disabled=page>=pages;if($('#visibleCount'))$('#visibleCount').textContent=filtered.length.toLocaleString('vi-VN');if($('#libraryCount'))$('#libraryCount').textContent=items.length.toLocaleString('vi-VN');if($('#ownedCount'))$('#ownedCount').textContent=owned.length.toLocaleString('vi-VN')}
function toggle(id){const k=String(id),i=owned.findIndex(v=>String(v)===k);if(i>=0)owned.splice(i,1);else owned.push(k);localStorage.setItem('aetheria_wardrobe',JSON.stringify(owned));filter();renderRank();notify(i>=0?'Đã bỏ khỏi tủ đồ':'Đã thêm vào tủ đồ')}
function detail(id){const x=items.find(v=>String(v.id)===String(id));if(!x)return;let d=$('#itemDetail');if(!d){d=document.createElement('dialog');d.id='itemDetail';d.className='item-detail';d.innerHTML='<div id="itemDetailContent"></div>';document.body.appendChild(d)}const has=owned.some(v=>String(v)===String(id)),aa=ATTRS.map(k=>({k,v:Number(x[k])||0})).sort((a,b)=>b.v-a.v),mx=Math.max(1,...aa.map(a=>a.v)),tags=Array.isArray(x.tags)?x.tags.filter(Boolean):[];$('#itemDetailContent').innerHTML=`<div class="detail-wrap"><div class="detail-media">${image(x.image,x.name)}</div><div class="detail-main"><button class="detail-close" onclick="document.getElementById('itemDetail').close()">×</button><div class="detail-kicker">CHI TIẾT ITEM</div><h3 class="detail-title">${esc(x.name)}</h3><div class="detail-meta">${esc(cat(x))}${x.suit?` • Bộ ${esc(x.suit)}`:''}</div><div class="detail-badges"><span class="detail-badge">${stars(x.rarity)}</span><span class="detail-badge">ID ${esc(x.id)}</span></div><div class="detail-section"><h4>10 thuộc tính</h4><div class="detail-attrs">${aa.map(a=>`<div class="detail-attr"><div class="detail-attr-top"><span>${LABEL[a.k]}</span><b>${a.v||'—'}</b></div><div class="detail-bar"><i style="width:${Math.min(100,a.v/mx*100)}%"></i></div></div>`).join('')}</div></div>${tags.length?`<div class="detail-section"><h4>Tag</h4><div class="detail-tags">${tags.map(t=>`<span class="detail-tag">${esc(t)}</span>`).join('')}</div></div>`:''}<div class="detail-actions"><button id="detailHeart">${has?'♥ Đã có trong tủ':'♡ Thêm vào tủ'}</button></div></div></div>`;$('#detailHeart').onclick=()=>{toggle(id);$('#detailHeart').textContent=owned.some(v=>String(v)===String(id))?'♥ Đã có trong tủ':'♡ Thêm vào tủ'};d.showModal()}
function setupCategories(){const cats=[...new Set(items.map(cat))].sort((a,b)=>a.localeCompare(b,'vi'));for(const id of ['categoryFilter','rankCategory','stageCategory']){const e=$('#'+id);if(!e)continue;const old=e.value||'all';e.innerHTML='<option value="all">Tất cả loại đồ</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if([...e.options].some(o=>o.value===old))e.value=old}}
function optimize(){const s=stages.find(x=>x.group===($('#stageTabs .active')?.dataset.stage||'aihoi'));const style=$('#styleFilter')?.value||'all',catv=$('#stageCategory')?.value||'all';let p=items.filter(x=>score(x)>0&&(catv==='all'||cat(x)===catv));if(s)p=p.map(x=>({...x,__fit:stageScore(x,s)})).filter(x=>x.__fit>0).sort((a,b)=>b.__fit-a.__fit);else if(style!=='all')p.sort((a,b)=>(Number(b[style])||0)-(Number(a[style])||0));if($('#optimizerResult'))$('#optimizerResult').innerHTML=s?`<b>${esc(s.label||s.name)}</b><div class="opt-list">${p.slice(0,8).map((x,i)=>`<div><span>#${i+1} ${esc(x.name)}</span><b>${Number(x.__fit||0).toLocaleString('vi-VN',{maximumFractionDigits:1})}</b></div>`).join('')}</div><small>Chỉ số tham khảo theo thuộc tính chặng.</small>`:style!=='all'?`<b>Top theo ${LABEL[style]}</b><div class="opt-list">${p.slice(0,8).map((x,i)=>`<div><span>#${i+1} ${esc(x.name)}</span><b>${Number(x[style])||0}</b></div>`).join('')}</div>`:'Chưa có stage profile đã xác minh cho nhóm này.'}
async function load(){try{const [d,s,e]=await Promise.all([fetch(DATA,{cache:'no-store'}),fetch(STAGES,{cache:'no-store'}),fetch(EXTRA,{cache:'no-store'})]);const p=await d.json();items=Array.isArray(p.items)?p.items:Array.isArray(p)?p:[];const base=s.ok?await s.json():{stages:[]};stages=Array.isArray(base.stages)?base.stages:[];if(e.ok){const q=await e.json(),seen=new Set(stages.map(x=>x.id));for(const x of(q.stages||[]))if(!seen.has(x.id))stages.push(x)}setupCategories();if($('#itemCount'))$('#itemCount').textContent=items.length.toLocaleString('vi-VN');if($('#heroStatus'))$('#heroStatus.innerHTML='<div>✓ '+items.length.toLocaleString('vi-VN')+' item trong dữ liệu</div><div>🇻🇳 Thuật ngữ tiếng Việt</div><div>🖼️ Ảnh từ nguồn công khai</div>';filter();renderRank();optimize()}catch(err){console.error(err);if($('#heroStatus'))$('#heroStatus').innerHTML='<div>⚠ Không tải được dữ liệu</div>';notify('Không tải được dữ liệu')}}
function menu(){const b=$('#menuBtn'),n=$('#nav');if(!b||!n)return;const close=()=>{n.classList.remove('open');b.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')};b.setAttribute('aria-controls','nav');b.setAttribute('aria-expanded','false');b.onclick=e=>{e.preventDefault();e.stopPropagation();const open=!n.classList.contains('open');n.classList.toggle('open',open);b.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)};n.onclick=e=>{if(e.target.closest('a'))close()};document.addEventListener('click',e=>{if(n.classList.contains('open')&&!n.contains(e.target)&&e.target!==b)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
function bind(){menu();document.addEventListener('click',e=>{const h=e.target.closest('[data-heart]');if(h){e.preventDefault();e.stopPropagation();toggle(h.dataset.heart);return}const c=e.target.closest('[data-item-id]');if(c&&!e.target.closest('button'))detail(c.dataset.itemId);const sc=e.target.closest('[data-scroll]');if(sc)document.getElementById(sc.dataset.scroll)?.scrollIntoView({behavior:'smooth'})});$$('#rankTabs button').forEach(b=>b.onclick=()=>{$$('#rankTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');group=b.dataset.rank;renderRank()});$('#rankLimit')?.addEventListener('change',renderRank);$('#rankCategory')?.addEventListener('change',renderRank);$('#rankChapterSelect')?.addEventListener('change',renderRank);$('#rankStageSelect')?.addEventListener('change',renderRank);$('#prevPage')?.addEventListener('click',()=>{if(page>1){page--;renderLibrary()}});$('#nextPage')?.addEventListener('click',()=>{const p=Math.max(1,Math.ceil(filtered.length/SIZE));if(page<p){page++;renderLibrary()}});['wardrobeSearch','categoryFilter','rarityFilter','ownershipFilter'].forEach(id=>{const e=$('#'+id);e?.addEventListener('input',()=>{page=1;filter()});e?.addEventListener('change',()=>{page=1;filter()})});$('#clearWardrobe')?.addEventListener('click',()=>{owned=[];localStorage.removeItem('aetheria_wardrobe');localStorage.removeItem('theealux_wardrobe');filter();renderRank();notify('Đã xóa tủ đồ')});$('#globalSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'){$('#wardrobeSearch').value=$('#globalSearch').value;page=1;filter();$('#wardrobe').scrollIntoView({behavior:'smooth'})}});$('#searchBtn')?.addEventListener('click',()=>{$('#wardrobeSearch').value=$('#globalSearch').value;page=1;filter();$('#wardrobe').scrollIntoView({behavior:'smooth'})});$('#themeBtn')?.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('aetheria_dark',document.body.classList.contains('dark'))});if(localStorage.getItem('aetheria_dark')==='true')document.body.classList.add('dark');$('#loginBtn')?.addEventListener('click',()=>$('#loginDialog')?.showModal());$('#optimizeBtn')?.addEventListener('click',optimize);$$('#stageTabs button').forEach(b=>b.onclick=()=>{$$('#stageTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');optimize()});$('#rankChapterSelect')?.addEventListener('change',renderRank)}
window.aetheriaRuntime={load,renderRank,filter,detail,optimize};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{bind();load()},{once:true});else{bind();load()}
})();