const DATA_URLS=['./data/items.json','https://raw.githubusercontent.com/lenlen2710208-cmyk/Theealux/main/data/items.json'];
const STAGES_URL='./data/stages.json';
const PAGE_SIZE=40;
const ATTRS=['gorgeous','simple','elegant','lively','mature','cute','sexy','pure','warm','cool'];
const ATTR_LABELS={gorgeous:'Hoa lệ',simple:'Giản dị',elegant:'Thanh lịch',lively:'Năng động',mature:'Trưởng thành',cute:'Dễ thương',sexy:'Quyến rũ',pure:'Thuần khiết',warm:'Ấm áp',cool:'Mát mẻ'};
const FALLBACK_IMG='data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22600%22 height=%22760%22%3E%3Crect width=%22600%22 height=%22760%22 fill=%22%23f0e1db%22/%3E%3Cpath d=%22M300 175c55 0 100 45 100 100s-45 100-100 100-100-45-100-100 45-100 100-100Zm-150 430c20-115 75-175 150-175s130 60 150 175Z%22 fill=%22%23c89aa3%22/%3E%3C/svg%3E';
let items=[],stageData={stages:[]},currentRank='aihoi',currentPage=1,libraryFiltered=[];
let wardrobe=JSON.parse(localStorage.getItem('aetheria_wardrobe')||localStorage.getItem('theealux_wardrobe')||'[]');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1800)}
function esc(v=''){return String(v).replace(/[&<>\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]||c))}
function img(url,name=''){return `<img loading="lazy" decoding="async" alt="${esc(name)}" src="${esc(url||FALLBACK_IMG)}" onerror="this.onerror=null;this.src='${FALLBACK_IMG}'">`}
function attrScore(x){return ATTRS.reduce((n,k)=>n+(Number(x[k])||0),0)}
function hasRealAttributes(x){return attrScore(x)>0}
function categoryOf(x){return String(x.category||x.typeName||x.type||'Chưa phân loại').trim()||'Chưa phân loại'}
function stars(r){const n=Math.max(0,Math.min(5,Number(r)||0));return n?'★'.repeat(n)+'☆'.repeat(5-n):'—'}
function topAttributes(x){return ATTRS.map(k=>({k,v:Number(x[k])||0})).filter(a=>a.v>0).sort((a,b)=>b.v-a.v).slice(0,4)}
function searchable(x){return [x.name,x.category,x.typeName,x.suit,x.style,x.source,Array.isArray(x.tags)?x.tags.join(' '):x.tags,...ATTRS.map(k=>ATTR_LABELS[k])].join(' ').toLowerCase()}
function stageFit(item,stage){if(!stage)return 0;return ATTRS.reduce((n,k)=>n+(Number(item[k])||0)*(Number(stage.attrs?.[k])||0),0)}
function selectedStage(){const id=$('#rankStageSelect')?.value;return stageData.stages.find(s=>s.id===id)||null}
function rankPool(){const stage=selectedStage();if(!stage)return [];let pool=items.filter(hasRealAttributes);const cat=$('#rankCategory')?.value||'all';if(cat!=='all')pool=pool.filter(x=>categoryOf(x)===cat);return pool.map(x=>({...x,__stageScore:stageFit(x,stage)})).filter(x=>x.__stageScore>0).sort((a,b)=>b.__stageScore-a.__stageScore||Number(b.rarity||0)-Number(a.rarity||0)||String(a.name).localeCompare(String(b.name),'vi'))}
function card(item,i,rank=false){const on=wardrobe.some(v=>String(v)===String(item.id));const top=rank?`<div class="rank-no">#${i+1}</div>`:'';const topAttrs=topAttributes(item);const attrs=topAttrs.map(a=>`${ATTR_LABELS[a.k]} ${a.v}`).join(' • ');const tags=Array.isArray(item.tags)?item.tags.filter(Boolean).slice(0,3).join(' • '):'';const metric=rank&&item.__stageScore!=null?`${item.__stageScore.toLocaleString('vi-VN',{maximumFractionDigits:1})} phù hợp chặng`:hasRealAttributes(item)?`${attrScore(item).toLocaleString('vi-VN')} điểm thuộc tính`:`${Number(item.rarity||0)}★ độ hiếm`;return `<article class="item-card ${rank?'rank-card':''}" data-item-id="${esc(item.id)}"><div class="item-img">${img(item.image,item.name)}<button class="heart ${on?'on':''}" data-heart="${esc(item.id)}" aria-label="${on?'Bỏ khỏi tủ đồ':'Lưu vào tủ đồ'}">${on?'♥':'♡'}</button></div><div class="item-body">${top}<div class="rank-name">${esc(item.name||'Chưa đặt tên')}</div><div class="meta">${esc(categoryOf(item))}${item.suit?` • ${esc(item.suit)}`:''}</div><div class="item-meta"><span class="rarity">${stars(item.rarity)}</span><span class="score">${metric}</span></div>${attrs?`<div class="attr-line">${esc(attrs)}</div>`:''}${tags?`<div class="meta">${esc(tags)}</div>`:''}</div></article>`}
function setupStageSelector(){let el=$('#rankStageSelect');if(!el){el=document.createElement('select');el.id='rankStageSelect';el.setAttribute('aria-label','Chọn chặng đã xác minh');$('#rankCategory')?.insertAdjacentElement('afterend',el)}const stages=stageData.stages.filter(s=>s.group===currentRank);el.innerHTML=stages.length?stages.map(s=>`<option value="${esc(s.id)}">${esc(s.label)} — ${esc(s.name)}</option>`).join(''):'<option value="">Chưa có dữ liệu đã xác minh</option>';if(stages.length)el.value=stages[0].id}
function renderRank(){const grid=$('#rankingGrid');if(!items.length){grid.innerHTML='<div class="empty">Chưa có dữ liệu item.</div>';return}setupStageSelector();const stage=selectedStage(),pool=rankPool();if(!stage){grid.innerHTML='<div class="empty">Chưa có dữ liệu chặng đã xác minh cho mục này. Aetheria không tự tạo bảng xếp hạng.</div>';$('#rankInfo').textContent='Chưa có stage profile đã xác minh';$('#rankDescription').textContent='Bảng chỉ xuất hiện khi có yêu cầu chặng từ nguồn tham khảo đã kiểm tra.';return}grid.innerHTML=pool.slice(0,20).map((x,i)=>card(x,i,true)).join('')||'<div class="empty">Không có item có thuộc tính phù hợp.</div>';$('#rankInfo').textContent=`Top 20 theo ${stage.label} • ${pool.length.toLocaleString('vi-VN')} item có thuộc tính`;$('#rankDescription').textContent=`${stage.label} — ${stage.name}. Xếp theo độ phù hợp với 5 thuộc tính của chặng; đây là chỉ số tra cứu item, không phải tổng điểm trận đấu.`}
function libraryFilter(){const q=($('#wardrobeSearch')?.value||'').trim().toLowerCase(),cat=$('#categoryFilter')?.value||'all',rarity=$('#rarityFilter')?.value||'all',own=$('#ownershipFilter')?.value||'all';libraryFiltered=items.filter(x=>{const owned=wardrobe.some(v=>String(v)===String(x.id));return(!q||searchable(x).includes(q))&&(cat==='all'||categoryOf(x)===cat)&&(rarity==='all'||String(x.rarity||'')===rarity)&&(own==='all'||(own==='owned'&&owned)||(own==='unowned'&&!owned))});currentPage=Math.min(currentPage,Math.max(1,Math.ceil(libraryFiltered.length/PAGE_SIZE)));renderLibrary()}
function renderLibrary(){const start=(currentPage-1)*PAGE_SIZE,page=libraryFiltered.slice(start,start+PAGE_SIZE);$('#wardrobeGrid').innerHTML=page.length?page.map((x,i)=>card(x,start+i,false)).join(''):'<div class="empty">Không tìm thấy item.</div>';const pages=Math.max(1,Math.ceil(libraryFiltered.length/PAGE_SIZE));$('#pageInfo').textContent=`Trang ${currentPage} / ${pages}`;$('#prevPage').disabled=currentPage<=1;$('#nextPage').disabled=currentPage>=pages;$('#visibleCount').textContent=libraryFiltered.length.toLocaleString('vi-VN');$('#libraryCount').textContent=items.length.toLocaleString('vi-VN');$('#ownedCount').textContent=wardrobe.length.toLocaleString('vi-VN')}
function toggleHeart(id){const key=String(id),pos=wardrobe.findIndex(v=>String(v)===key);if(pos>=0)wardrobe.splice(pos,1);else wardrobe.push(key);localStorage.setItem('aetheria_wardrobe',JSON.stringify(wardrobe));renderRank();libraryFilter();toast(pos>=0?'Đã bỏ khỏi tủ đồ':'Đã thêm vào tủ đồ')}
function search(){const q=$('#globalSearch').value.trim().toLowerCase();$('#wardrobeSearch').value=q;$('#ownershipFilter').value='all';libraryFilter();$('#wardrobe').scrollIntoView({behavior:'smooth'});if(q)toast(`Đã lọc theo “${q}”`)}
document.addEventListener('click',e=>{const h=e.target.closest('[data-heart]');if(h){e.preventDefault();e.stopPropagation();toggleHeart(h.dataset.heart);return}const c=e.target.closest('[data-item-id]');if(c&&!e.target.closest('button'))openItemDetail(c.dataset.itemId);const sc=e.target.closest('[data-scroll]');if(sc)document.getElementById(sc.dataset.scroll)?.scrollIntoView({behavior:'smooth'})});
$$('#rankTabs button').forEach(b=>b.onclick=()=>{$$('#rankTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentRank=b.dataset.rank;renderRank()});
$('#rankCategory').onchange=renderRank;
$('#prevPage').onclick=()=>{if(currentPage>1){currentPage--;renderLibrary()}};$('#nextPage').onclick=()=>{const pages=Math.max(1,Math.ceil(libraryFiltered.length/PAGE_SIZE));if(currentPage<pages){currentPage++;renderLibrary()}};
['wardrobeSearch','categoryFilter','rarityFilter','ownershipFilter'].forEach(id=>{const el=$('#'+id);el.oninput=el.onchange=()=>{currentPage=1;libraryFilter()}});
$('#clearWardrobe').onclick=()=>{wardrobe=[];localStorage.removeItem('aetheria_wardrobe');localStorage.removeItem('theealux_wardrobe');renderRank();libraryFilter();toast('Đã xóa tủ đồ')};$('#globalSearch').onkeydown=e=>{if(e.key==='Enter')search()};$('#searchBtn').onclick=search;
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('aetheria_dark',document.body.classList.contains('dark'))};if(localStorage.getItem('aetheria_dark')==='true'||localStorage.getItem('theealux_dark')==='true')document.body.classList.add('dark');
$('#loginBtn').onclick=()=>$('#loginDialog').showModal();$('#loginSubmit').onclick=()=>{localStorage.setItem('aetheria_demo_user',$('#email').value);toast('Đã lưu phiên demo trên thiết bị')};$('#menuBtn').onclick=()=>$('.nav').classList.toggle('open');
function optimize(){const style=$('#styleFilter').value,cat=$('#stageCategory').value,stage=stageData.stages.find(s=>s.group===$('#stageTabs .active')?.dataset.stage);let pool=items.filter(x=>(cat==='all'||categoryOf(x)===cat)&&hasRealAttributes(x));if(stage){pool=pool.map(x=>({...x,__stageScore:stageFit(x,stage)})).filter(x=>x.__stageScore>0).sort((a,b)=>b.__stageScore-a.__stageScore);$('#optimizerResult').innerHTML=`<b>${stage.label} — ${stage.name}</b><div class="opt-list">${pool.slice(0,5).map((x,i)=>`<div><span>#${i+1} ${esc(x.name)}</span><b>${x.__stageScore.toLocaleString('vi-VN',{maximumFractionDigits:1})}</b></div>`).join('')}</div><small>Chỉ số phù hợp được tính từ thuộc tính chặng đã xác minh; không giả làm điểm trận đấu.</small>`}else if(style!=='all'){pool.sort((a,b)=>(Number(b[style])||0)-(Number(a[style])||0));$('#optimizerResult').innerHTML=`<b>Gợi ý theo ${ATTR_LABELS[style]}</b><div class="opt-list">${pool.slice(0,5).map((x,i)=>`<div><span>#${i+1} ${esc(x.name)}</span><b>${Number(x[style])||0}</b></div>`).join('')}</div>`}else $('#optimizerResult').textContent='Chưa có stage profile đã xác minh cho nhóm này.'}
$('#optimizeBtn').onclick=optimize;$$('#stageTabs button').forEach(b=>b.onclick=()=>{$$('#stageTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');optimize()});
function ensureDetailUI(){if($('#itemDetail'))return;const s=document.createElement('style');s.textContent='.item-detail{border:0;border-radius:28px;padding:0;width:min(920px,calc(100% - 28px));max-height:88vh;background:var(--card,#fffaf6);color:var(--text,#34292c);box-shadow:0 28px 90px rgba(50,35,40,.28)}.item-detail::backdrop{background:rgba(38,25,30,.58);backdrop-filter:blur(5px)}.detail-wrap{display:grid;grid-template-columns:minmax(220px,300px) 1fr;gap:28px;padding:26px}.detail-media{display:flex;align-items:center;justify-content:center;background:var(--soft,#eee0da);border-radius:22px;min-height:330px;overflow:hidden}.detail-media img{width:100%;height:100%;max-height:560px;object-fit:contain}.detail-main{min-width:0}.detail-close{float:right;border:0;background:var(--soft,#eee0da);border-radius:50%;width:38px;height:38px;font-size:22px;cursor:pointer}.detail-kicker{font-size:12px;font-weight:800;letter-spacing:.14em;color:var(--primary,#9a5966);text-transform:uppercase}.detail-title{font-family:Playfair Display,serif;font-size:clamp(25px,4vw,38px);margin:7px 45px 5px 0}.detail-meta{color:var(--muted,#7b6b6f);line-height:1.6}.detail-badges{display:flex;flex-wrap:wrap;gap:8px;margin:15px 0}.detail-badge{padding:7px 10px;border-radius:999px;background:var(--soft,#eee0da);font-size:13px;font-weight:700}.detail-attrs{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:18px}.detail-attr{padding:11px 12px;border:1px solid var(--line,#e7d8d0);border-radius:13px}.detail-attr-top{display:flex;justify-content:space-between;font-size:13px}.detail-bar{height:6px;border-radius:99px;background:var(--soft,#eee0da);margin-top:7px;overflow:hidden}.detail-bar i{display:block;height:100%;background:linear-gradient(90deg,var(--primary,#9a5966),var(--accent,#c79a68))}.detail-section{margin-top:20px}.detail-section h4{margin:0 0 8px}.detail-tags{display:flex;flex-wrap:wrap;gap:7px}.detail-tag{font-size:12px;padding:6px 9px;border-radius:8px;background:var(--card2,#fcf3ed)}.detail-actions button{border:0;border-radius:12px;padding:11px 15px;background:var(--primary,#9a5966);color:white;font-weight:700;cursor:pointer}@media(max-width:680px){.detail-wrap{grid-template-columns:1fr;gap:16px;padding:18px}.detail-media{min-height:240px;max-height:330px}.detail-attrs{grid-template-columns:1fr}}';document.head.appendChild(s);const d=document.createElement('dialog');d.id='itemDetail';d.className='item-detail';d.innerHTML='<div id="itemDetailContent"></div>';document.body.appendChild(d);d.onclick=e=>{if(e.target===d)d.close()}}
function openItemDetail(id){ensureDetailUI();const x=items.find(v=>String(v.id)===String(id));if(!x)return;const owned=wardrobe.some(v=>String(v)===String(x.id)),attrs=ATTRS.map(k=>({k,v:Number(x[k])||0})).sort((a,b)=>b.v-a.v),max=Math.max(1,...attrs.map(a=>a.v)),tags=Array.isArray(x.tags)?x.tags.filter(Boolean):[];$('#itemDetailContent').innerHTML=`<div class="detail-wrap"><div class="detail-media">${img(x.image,x.name)}</div><div class="detail-main"><button class="detail-close" onclick="document.getElementById('itemDetail').close()">×</button><div class="detail-kicker">Chi tiết vật phẩm</div><h3 class="detail-title">${esc(x.name||'Chưa đặt tên')}</h3><div class="detail-meta">${esc(categoryOf(x))}${x.suit?` • Bộ ${esc(x.suit)}`:''}</div><div class="detail-badges"><span class="detail-badge">${stars(x.rarity)}</span><span class="detail-badge">Tổng ${attrScore(x).toLocaleString('vi-VN')}</span>${x.id?`<span class="detail-badge">ID ${esc(x.id)}</span>`:''}</div><div class="detail-section"><h4>10 thuộc tính</h4><div class="detail-attrs">${attrs.map(a=>`<div class="detail-attr"><div class="detail-attr-top"><span>${ATTR_LABELS[a.k]}</span><b>${a.v||'—'}</b></div><div class="detail-bar"><i style="width:${Math.min(100,a.v/max*100)}%"></i></div></div>`).join('')}</div></div>${tags.length?`<div class="detail-section"><h4>Tag</h4><div class="detail-tags">${tags.map(t=>`<span class="detail-tag">${esc(t)}</span>`).join('')}</div></div>`:''}<div class="detail-section"><h4>Thông tin</h4><div class="detail-meta">Độ hiếm: ${Number(x.rarity)||'Chưa có dữ liệu'} sao<br>Loại: ${esc(categoryOf(x))}${x.suit?`<br>Bộ trang phục: ${esc(x.suit)}`:''}</div></div><div class="detail-actions"><button id="detailHeart">${owned?'♥ Đã có trong tủ':'♡ Thêm vào tủ'}</button></div></div></div>`;$('#detailHeart').onclick=()=>{toggleHeart(x.id);$('#detailHeart').textContent=wardrobe.some(v=>String(v)===String(x.id))?'♥ Đã có trong tủ':'♡ Thêm vào tủ'};$('#itemDetail').showModal()}
async function loadStages(){try{const r=await fetch(STAGES_URL,{cache:'no-store'});if(!r.ok)throw 0;stageData=await r.json()}catch(e){stageData={stages:[]}}}
async function boot(){await loadStages();let lastError=null;for(const url of DATA_URLS){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`dataset ${r.status}`);const payload=await r.json();items=Array.isArray(payload.items)?payload.items:[];if(!items.length)throw new Error('dataset rỗng');const count=Number(payload.count||items.length);$('#itemCount').textContent=count.toLocaleString('vi-VN');$('#heroStatus').innerHTML=`<div>✓ ${count.toLocaleString('vi-VN')} item trong dữ liệu</div><div>🔎 Dữ liệu item từ nguồn công khai</div><div>🖼️ Ưu tiên ảnh chất lượng cao</div>`;renderRank();libraryFilter();optimize();return}catch(e){lastError=e}}$('#itemCount').textContent='0';$('#heroStatus').innerHTML='<div>⚠ Không tải được dữ liệu</div>';toast('Không tải được dataset');console.error(lastError)}}
boot();