/* Aetheria — stable UI/runtime layer. Data remains source-driven; no fabricated stages/items. */
(()=>{
'use strict';
const DATA_URLS=['./data/items.json','https://raw.githubusercontent.com/lenlen2710208-cmyk/Theealux/main/data/items.json'];
const STAGES_URL='./data/stages.json'; const STAGE_EXTRAS_URL='./data/stages-extra.json';
const PAGE_SIZE=40;
const ATTRS=['gorgeous','simple','elegant','lively','mature','cute','sexy','pure','warm','cool'];
const ATTR_LABELS={gorgeous:'Quý phái',simple:'Đơn giản',elegant:'Thanh lịch',lively:'Năng động',mature:'Trưởng thành',cute:'Dễ thương',sexy:'Gợi cảm',pure:'Trong sáng',warm:'Giữ ấm',cool:'Mát mẻ'};
const GROUP_LABELS={aihoi:'Ải hội',quyen1:'Quyển 1',quyen2:'Quyển 2',thidau:'Khu thi đấu'};
const FALLBACK_IMG='data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22600%22 height=%22760%22%3E%3Crect width=%22600%22 height=%22760%22 fill=%22%23f0e1db%22/%3E%3Cpath d=%22M300 175c55 0 100 45 100 100s-45 100-100 100-100-45-100-100 45-100 100-100Zm-150 430c20-115 75-175 150-175s130 60 150 175Z%22 fill=%22%23c89aa3%22/%3E%3C/svg%3E';
let items=[],stageData={stages:[]},currentRank='aihoi',currentPage=1,libraryFiltered=[],rankStageMemory={};
let wardrobe=[]; try{wardrobe=JSON.parse(localStorage.getItem('aetheria_wardrobe')||localStorage.getItem('theealux_wardrobe')||'[]')}catch(_){wardrobe=[]}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window.__aToast);window.__aToast=setTimeout(()=>x.classList.remove('show'),1800)}
function img(url,name=''){return `<img loading="lazy" decoding="async" alt="${esc(name)}" src="${esc(url||FALLBACK_IMG)}" onerror="this.onerror=null;this.src='${FALLBACK_IMG}'">`}
function attrScore(x){return ATTRS.reduce((n,k)=>n+(Number(x?.[k])||0),0)}
function hasAttrs(x){return attrScore(x)>0}
function categoryOf(x){return String(x?.category||x?.typeName||x?.type||'Chưa phân loại').trim()||'Chưa phân loại'}
function stars(r){const n=Math.max(0,Math.min(5,Number(r)||0));return n?'★'.repeat(n)+'☆'.repeat(5-n):'—'}
function topAttrs(x){return ATTRS.map(k=>({k,v:Number(x?.[k])||0})).filter(a=>a.v>0).sort((a,b)=>b.v-a.v).slice(0,3)}
function searchable(x){return [x.name,x.category,x.typeName,x.type,x.suit,x.style,x.source,Array.isArray(x.tags)?x.tags.join(' '):x.tags,...ATTRS.map(k=>ATTR_LABELS[k])].join(' ').toLowerCase()}
function stageFit(item,stage){if(!stage)return 0;return ATTRS.reduce((n,k)=>n+(Number(item?.[k])||0)*(Number(stage.attrs?.[k])||0),0)}
function selectedStage(){const id=$('#rankStageSelect')?.value;return stageData.stages.find(s=>String(s.id)===String(id))||null}
function stageKey(s){return String(s?.chapter||s?.chapterId||s?.groupChapter||s?.chapterLabel||'')}
function stageChapter(s){const m=String(s?.label||'').match(/(Chương\s*[^•]+|Chương\s*\d+)/i);return m?m[1].trim():stageKey(s)||'Khác'}
function stageIsTheme(s){return currentRank==='thidau'||s?.type==='theme'||s?.kind==='theme'||s?.theme===true}
function categoryOptions(){const el=$('#rankCategory');if(!el)return;const cats=[...new Set(items.map(categoryOf).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'vi'));const old=el.value||'all';el.innerHTML='<option value="all">Tất cả loại đồ</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');el.value=cats.includes(old)?old:'all';if($('#stageCategory'))$('#stageCategory').innerHTML=el.innerHTML}
function setupRankSelectors(){
 const ch=$('#rankChapterSelect'), st=$('#rankStageSelect'); if(!ch||!st)return;
 const stages=stageData.stages.filter(s=>s.group===currentRank);
 const chapters=[...new Map(stages.map(s=>[stageChapter(s),s])).keys()];
 const oldCh=ch.value, oldSt=rankStageMemory[currentRank]||st.value;
 ch.innerHTML=chapters.length?chapters.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join(''):'<option value="">Chưa có dữ liệu</option>';
 const selectedChapter=chapters.includes(oldCh)?oldCh:chapters[0]||''; ch.value=selectedChapter;
 const subset=stages.filter(s=>stageChapter(s)===selectedChapter);
 st.innerHTML=subset.length?subset.map(s=>`<option value="${esc(s.id)}">${esc(s.label||s.name||s.id)}</option>`).join(''):'<option value="">Chưa có chặng đã xác minh</option>';
 if(subset.length)st.value=subset.some(s=>String(s.id)===String(oldSt))?oldSt:subset[0].id;
 ch.onchange=()=>{rankStageMemory[currentRank]='';setupRankSelectors();renderRank()};
 st.onchange=()=>{rankStageMemory[currentRank]=st.value;renderRank()};
}
function rankPool(){const stage=selectedStage();if(!stage)return[];let pool=items.filter(hasAttrs);const cat=$('#rankCategory')?.value||'all';if(cat!=='all')pool=pool.filter(x=>categoryOf(x)===cat);return pool.map(x=>({...x,__stageScore:stageFit(x,stage)})).filter(x=>x.__stageScore>0).sort((a,b)=>b.__stageScore-a.__stageScore||Number(b.rarity||0)-Number(a.rarity||0)||String(a.name).localeCompare(String(b.name),'vi'))}
function card(item,i,rank=false){const on=wardrobe.some(v=>String(v)===String(item.id));const attrs=topAttrs(item).map(a=>`${ATTR_LABELS[a.k]} ${a.v}`).join(' • ');const tags=Array.isArray(item.tags)?item.tags.filter(Boolean).slice(0,3).join(' • '):'';const metric=rank?`${Number(item.__stageScore||0).toLocaleString('vi-VN',{maximumFractionDigits:1})} phù hợp`:attrScore(item)?`${attrScore(item).toLocaleString('vi-VN')} thuộc tính`:`${Number(item.rarity||0)}★`;return `<article class="item-card ${rank?'rank-card':''}" data-item-id="${esc(item.id)}"><div class="item-img">${img(item.image,item.name)}<button class="heart ${on?'on':''}" data-heart="${esc(item.id)}" aria-label="${on?'Bỏ khỏi tủ đồ':'Lưu vào tủ đồ'}">${on?'♥':'♡'}</button></div><div class="item-body">${rank?`<div class="rank-no">#${i+1}</div>`:''}<div class="rank-name">${esc(item.name||'Chưa đặt tên')}</div><div class="meta">${esc(categoryOf(item))}${item.suit?` • ${esc(item.suit)}`:''}</div><div class="item-meta"><span class="rarity">${stars(item.rarity)}</span><span class="score">${metric}</span></div>${attrs?`<div class="attr-line">${esc(attrs)}</div>`:''}${tags?`<div class="meta">${esc(tags)}</div>`:''}</div></article>`}
function renderRank(){const grid=$('#rankingGrid');if(!grid)return;if(!items.length){grid.innerHTML='<div class="empty">Đang chờ dữ liệu item…</div>';return}setupRankSelectors();const stage=selectedStage(),pool=rankPool();if(!stage){grid.innerHTML='<div class="empty">Nhóm này chưa có stage/theme đã xác minh. Aetheria không tự bịa dữ liệu.</div>';if($('#rankInfo'))$('#rankInfo').textContent='Chưa có dữ liệu stage/theme đã xác minh';return}const limit=Number($('#rankLimit')?.value||20);grid.innerHTML=pool.slice(0,limit).map((x,i)=>card(x,i,true)).join('')||'<div class="empty">Không có item phù hợp.</div>';const weights=ATTRS.map(k=>[k,Number(stage.attrs?.[k])||0]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]);if($('#rankInfo'))$('#rankInfo').textContent=`${stage.label||stage.name} • ${pool.length.toLocaleString('vi-VN')} item • Ưu tiên ${weights.slice(0,2).map(x=>ATTR_LABELS[x[0]]).join(' + ')}`;if($('#rankDescription'))$('#rankDescription').textContent=`${stage.label||''} — ${stage.name||''}. Top được tính từ trọng số thuộc tính của đúng chặng/theme; đây là chỉ số phù hợp tham khảo, không phải điểm trận đấu.`}
function libraryFilter(){const q=($('#wardrobeSearch')?.value||'').trim().toLowerCase(),cat=$('#categoryFilter')?.value||'all',rar=$('#rarityFilter')?.value||'all',own=$('#ownershipFilter')?.value||'all';libraryFiltered=items.filter(x=>{const owned=wardrobe.some(v=>String(v)===String(x.id));return(!q||searchable(x).includes(q))&&(cat==='all'||categoryOf(x)===cat)&&(rar==='all'||String(x.rarity||'')===rar)&&(own==='all'||(own==='owned'&&owned)||(own==='unowned'&&!owned))});currentPage=Math.min(currentPage,Math.max(1,Math.ceil(libraryFiltered.length/PAGE_SIZE)));renderLibrary()}
function renderLibrary(){const grid=$('#wardrobeGrid');if(!grid)return;const start=(currentPage-1)*PAGE_SIZE,page=libraryFiltered.slice(start,start+PAGE_SIZE),pages=Math.max(1,Math.ceil(libraryFiltered.length/PAGE_SIZE));grid.innerHTML=page.length?page.map((x,i)=>card(x,start+i,false)).join(''):'<div class="empty">Không tìm thấy item.</div>';if($('#pageInfo'))$('#pageInfo').textContent=`Trang ${currentPage} / ${pages}`;if($('#prevPage'))$('#prevPage').disabled=currentPage<=1;if($('#nextPage'))$('#nextPage').disabled=currentPage>=pages;if($('#visibleCount'))$('#visibleCount').textContent=libraryFiltered.length.toLocaleString('vi-VN');if($('#libraryCount'))$('#libraryCount').textContent=items.length.toLocaleString('vi-VN');if($('#ownedCount'))$('#ownedCount').textContent=wardrobe.length.toLocaleString('vi-VN')}
function toggleHeart(id){const key=String(id),i=wardrobe.findIndex(v=>String(v)===key);if(i>=0)wardrobe.splice(i,1);else wardrobe.push(key);localStorage.setItem('aetheria_wardrobe',JSON.stringify(wardrobe));libraryFilter();renderRank();toast(i>=0?'Đã bỏ khỏi tủ đồ':'Đã thêm vào tủ đồ')}
function search(){const q=$('#globalSearch')?.value.trim()||'';if($('#wardrobeSearch'))$('#wardrobeSearch').value=q;currentPage=1;libraryFilter();$('#wardrobe')?.scrollIntoView({behavior:'smooth'});if(q)toast(`Đã lọc theo “${q}”`)}
function openItemDetail(id){const x=items.find(v=>String(v.id)===String(id));if(!x)return;ensureDetailUI();const d=$('#itemDetail');const owned=wardrobe.some(v=>String(v)===String(x.id));const attrs=ATTRS.map(k=>({k,v:Number(x[k])||0})).sort((a,b)=>b.v-a.v),max=Math.max(1,...attrs.map(a=>a.v)),tags=Array.isArray(x.tags)?x.tags.filter(Boolean):[];$('#itemDetailContent').innerHTML=`<div class="detail-wrap"><div class="detail-media">${img(x.image,x.name)}</div><div class="detail-main"><button class="detail-close" onclick="document.getElementById('itemDetail').close()">×</button><div class="detail-kicker">Chi tiết vật phẩm</div><h3 class="detail-title">${esc(x.name||'Chưa đặt tên')}</h3><div class="detail-meta">${esc(categoryOf(x))}${x.suit?` • Bộ ${esc(x.suit)}`:''}</div><div class="detail-badges"><span class="detail-badge">${stars(x.rarity)}</span><span class="detail-badge">Tổng ${attrScore(x).toLocaleString('vi-VN')}</span><span class="detail-badge">ID ${esc(x.id)}</span></div><div class="detail-section"><h4>10 thuộc tính</h4><div class="detail-attrs">${attrs.map(a=>`<div class="detail-attr"><div class="detail-attr-top"><span>${ATTR_LABELS[a.k]}</span><b>${a.v||'—'}</b></div><div class="detail-bar"><i style="width:${Math.min(100,a.v/max*100)}%"></i></div></div>`).join('')}</div></div>${tags.length?`<div class="detail-section"><h4>Tag</h4><div class="detail-tags">${tags.map(t=>`<span class="detail-tag">${esc(t)}</span>`).join('')}</div></div>`:''}<div class="detail-actions"><button id="detailHeart">${owned?'♥ Đã có trong tủ':'♡ Thêm vào tủ'}</button></div></div></div>`;$('#detailHeart').onclick=()=>{toggleHeart(x.id);$('#detailHeart').textContent=wardrobe.some(v=>String(v)===String(x.id))?'♥ Đã có trong tủ':'♡ Thêm vào tủ'};d.showModal()}
function ensureDetailUI(){if($('#itemDetail'))return;const d=document.createElement('dialog');d.id='itemDetail';d.className='item-detail';d.innerHTML='<div id="itemDetailContent"></div>';document.body.appendChild(d)}
function optimize(){const group=$('#stageTabs .active')?.dataset.stage||'aihoi',style=$('#styleFilter')?.value||'all',cat=$('#stageCategory')?.value||'all';let pool=items.filter(x=>(cat==='all'||categoryOf(x)===cat)&&hasAttrs(x));const stage=stageData.stages.find(s=>s.group===group);if(stage){pool=pool.map(x=>({...x,__stageScore:stageFit(x,stage)})).filter(x=>x.__stageScore>0).sort((a,b)=>b.__stageScore-a.__stageScore);$('#optimizerResult').innerHTML=`<b>${esc(stage.label||stage.name)}</b><div class="opt-list">${pool.slice(0,8).map((x,i)=>`<div><span>#${i+1} ${esc(x.name)}</span><b>${x.__stageScore.toLocaleString('vi-VN',{maximumFractionDigits:1})}</b></div>`).join('')}</div><small>Chỉ số tham khảo từ thuộc tính chặng đã xác minh.</small>`}else if(style!=='all'){pool.sort((a,b)=>(Number(b[style])||0)-(Number(a[style])||0));$('#optimizerResult').innerHTML=`<b>Top theo ${ATTR_LABELS[style]}</b><div class="opt-list">${pool.slice(0,8).map((x,i)=>`<div><span>#${i+1} ${esc(x.name)}</span><b>${Number(x[style])||0}</b></div>`).join('')}</div>`}else $('#optimizerResult').textContent='Chưa có stage profile đã xác minh cho nhóm này.'}
async function loadStages(){try{const [a,b]=await Promise.all([fetch(STAGES_URL,{cache:'no-store'}),fetch(STAGE_EXTRAS_URL,{cache:'no-store'})]);stageData=a.ok?await a.json():{stages:[]};if(!Array.isArray(stageData.stages))stageData.stages=[];if(b.ok){const extra=await b.json();const seen=new Set(stageData.stages.map(s=>s.id));for(const s of (extra.stages||[]))if(!seen.has(s.id)){stageData.stages.push(s);seen.add(s.id)}}}catch(e){console.error(e);stageData={stages:[]}}}
async function boot(){if(window.__aetheriaBooting)return;window.__aetheriaBooting=true;await loadStages();let err=null;for(const url of DATA_URLS){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(`dataset ${r.status}`);const p=await r.json();items=Array.isArray(p.items)?p.items:(Array.isArray(p)?p:[]);if(!items.length)throw Error('dataset rỗng');const count=Number(p.count)||items.length;if($('#itemCount'))$('#itemCount').textContent=count.toLocaleString('vi-VN');if($('#libraryCount'))$('#libraryCount').textContent=count.toLocaleString('vi-VN');if($('#heroStatus'))$('#heroStatus').innerHTML=`<div>✓ ${count.toLocaleString('vi-VN')} item trong dữ liệu</div><div>🇻🇳 Thuật ngữ tiếng Việt</div><div>🖼️ Ảnh từ nguồn công khai</div>`;categoryOptions();libraryFilter();renderRank();optimize();window.__aetheriaReady=true;return}catch(e){err=e}}if($('#heroStatus'))$('#heroStatus.innerHTML='<div>⚠ Không tải được dữ liệu</div>');console.error(err);toast('Không tải được dữ liệu item')}
function bind(){
 document.addEventListener('click',e=>{const h=e.target.closest('[data-heart]');if(h){e.preventDefault();e.stopPropagation();toggleHeart(h.dataset.heart);return}const c=e.target.closest('[data-item-id]');if(c&&!e.target.closest('button'))openItemDetail(c.dataset.itemId);const sc=e.target.closest('[data-scroll]');if(sc)document.getElementById(sc.dataset.scroll)?.scrollIntoView({behavior:'smooth'})});
 $$('#rankTabs button').forEach(b=>b.addEventListener('click',()=>{$$('#rankTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentRank=b.dataset.rank;currentPage=1;renderRank()}));
 $('#rankLimit')?.addEventListener('change',renderRank); $('#rankCategory')?.addEventListener('change',renderRank);
 $('#prevPage')?.addEventListener('click',()=>{if(currentPage>1){currentPage--;renderLibrary()}}); $('#nextPage')?.addEventListener('click',()=>{const p=Math.max(1,Math.ceil(libraryFiltered.length/PAGE_SIZE));if(currentPage<p){currentPage++;renderLibrary()}});
 ['wardrobeSearch','categoryFilter','rarityFilter','ownershipFilter'].forEach(id=>{const el=$('#'+id);if(el)el.addEventListener('input',()=>{currentPage=1;libraryFilter()});if(el)el.addEventListener('change',()=>{currentPage=1;libraryFilter()})});
 $('#clearWardrobe')?.addEventListener('click',()=>{wardrobe=[];localStorage.removeItem('aetheria_wardrobe');localStorage.removeItem('theealux_wardrobe');libraryFilter();renderRank();toast('Đã xóa tủ đồ')});
 $('#globalSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')search()});$('#searchBtn')?.addEventListener('click',search);
 $('#themeBtn')?.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('aetheria_dark',document.body.classList.contains('dark'))});if(localStorage.getItem('aetheria_dark')==='true'||localStorage.getItem('theealux_dark')==='true')document.body.classList.add('dark');
 $('#loginBtn')?.addEventListener('click',()=>$('#loginDialog')?.showModal());
 $('#optimizeBtn')?.addEventListener('click',optimize); $$('#stageTabs button').forEach(b=>b.addEventListener('click',()=>{$$('#stageTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');optimize()}));
 const menu=$('#menuBtn'),nav=$('#nav');if(menu&&nav){const close=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')};menu.setAttribute('aria-controls','nav');menu.setAttribute('aria-expanded','false');menu.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const open=!nav.classList.contains('open');nav.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});nav.addEventListener('click',e=>{if(e.target.closest('a'))close()});document.addEventListener('click',e=>{if(nav.classList.contains('open')&&!nav.contains(e.target)&&e.target!==menu)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
}
window.optimize=optimize;window.boot=boot;window.openItemDetail=openItemDetail;
function start(){bind();boot()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();