/* Aetheria UI + ranking integrity layer. Never present a proxy attribute sum as real battle score. */
(function(){
const BUILD='2026.09.17-r82';
const esc=v=>String(v??'').replace(/[&<>\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]||c));
const chapterOf=s=>{const t=String(s?.label||s?.name||''),m=t.match(/Chương\s*(\d+)/i);if(m)return `Chương ${m[1]}`;const id=String(s?.id||''),v=id.match(/^v\d+-(\d+)-/i);if(v)return `Chương ${v[1]}`;const g=id.match(/^(?:guild|aihoi|gh|g)-(\d+)/i);if(g)return `Chương ${g[1]}`;return 'Khác'};
const exactItem=x=>!!x&&(!!x.internalParams||!!x.internal||!!x.internal_parameters||!!x.internalScore||!!x.scoreParams||!!x.partScores);
const exactStage=s=>!!s&&!!s.attrs&&!!(s.judgmentCoefficients||s.judgementCoefficients||s.judgment||s.opponent||s.opponentScore||s.opponentSkills||s.skillEffects||s.tagCoefficients);
const ready=s=>!!s&&exactStage(s)&&Array.isArray(items)&&items.length>0&&items.some(exactItem);
function premium(){if(document.getElementById('aetheria-r82-style'))return;const st=document.createElement('style');st.id='aetheria-r82-style';st.textContent=`
.section{animation:aetheria-in .65s ease both}@keyframes aetheria-in{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}}
.topbar{backdrop-filter:blur(18px) saturate(1.2);transition:box-shadow .25s,background .25s}.topbar.scrolled{box-shadow:0 12px 35px rgba(70,40,48,.13)}
.sparkle{animation:aetheria-spark 1.8s ease-in-out infinite}.art-glow{animation:aetheria-glow 4s ease-in-out infinite}@keyframes aetheria-spark{0%,100%{opacity:.35;transform:scale(.8) rotate(0)}50%{opacity:1;transform:scale(1.15) rotate(18deg)}}@keyframes aetheria-glow{0%,100%{transform:scale(.98);opacity:.65}50%{transform:scale(1.05);opacity:.95}}
.item-card,.feature-card,.source-card,.stage-panel,.hero-card{transition:transform .28s ease,box-shadow .28s ease,border-color .28s ease}.item-card:hover,.feature-card:hover,.source-card:hover{transform:translateY(-6px);box-shadow:0 18px 45px rgba(91,55,64,.14)}
.rank-toolbar{display:flex;flex-wrap:wrap;gap:10px;align-items:center}.rank-toolbar select{min-width:150px}.rank-stage-hierarchy{display:contents}.rank-card{animation:aetheria-card .45s ease both}@keyframes aetheria-card{from{opacity:0;transform:translateY(9px) scale(.985)}to{opacity:1;transform:none}}
.build-status{font-size:11px!important;opacity:.85;margin-top:5px}.data-integrity{margin-top:8px;padding:9px 11px;border:1px solid var(--line,#e7d8d0);border-radius:12px;background:var(--card2,#fcf3ed);font-size:12px}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
`;document.head.appendChild(st);window.addEventListener('scroll',()=>document.querySelector('.topbar')?.classList.toggle('scrolled',scrollY>8),{passive:true})}
function status(){const h=document.querySelector('#heroStatus');if(!h)return;let e=h.querySelector('.build-status');if(!e){e=document.createElement('div');e.className='build-status';h.appendChild(e)}e.textContent=`✓ Aetheria ${BUILD} • dữ liệu 32K+ được giữ nguyên`}
function hierarchy(){document.querySelector('#rankStageSelect')?.remove();const cat=document.querySelector('#rankCategory');if(!cat)return;let w=document.querySelector('#rankStageHierarchy');if(!w){w=document.createElement('div');w.id='rankStageHierarchy';w.className='rank-stage-hierarchy';cat.insertAdjacentElement('afterend',w)}const stages=(stageData?.stages||[]).filter(s=>s.group===currentRank),comp=currentRank==='thidau',chapters=[...new Set(stages.map(chapterOf))],old=window.__aetheriaSelectedStage||'';w.innerHTML='<select id="rankChapterSelect" aria-label="Chọn chương hoặc chủ đề"></select><select id="rankExactStageSelect" aria-label="Chọn ải hoặc chủ đề cụ thể"></select>';const ch=document.querySelector('#rankChapterSelect'),st=document.querySelector('#rankExactStageSelect');ch.innerHTML=chapters.length?chapters.map(x=>`<option value="${esc(x)}">${esc(comp?'Chủ đề':x)}</option>`).join(''):'<option value="">Chưa có dữ liệu</option>';const wanted=stages.find(s=>s.id===old);if(wanted)ch.value=chapterOf(wanted);const fill=()=>{const list=stages.filter(s=>chapterOf(s)===(ch.value||chapters[0]));st.innerHTML=list.length?list.map(s=>`<option value="${esc(s.id)}">${esc(s.label||s.name||s.id)}</option>`).join(''):'<option value="">Chưa có ải đã xác minh</option>';if(list.some(s=>s.id===old))st.value=old;window.__aetheriaSelectedStage=st.value||''};fill();ch.onchange=()=>{window.__aetheriaSelectedStage='';fill();window.renderRank()};st.onchange=()=>{window.__aetheriaSelectedStage=st.value;window.renderRank()}}
function limit(){const n=Number(document.querySelector('#rankLimit')?.value||20);return [20,50,100].includes(n)?n:20}
window.aetheriaRankingReady=ready;window.aetheriaExactItem=exactItem;window.aetheriaExactStage=exactStage;window.aetheriaStageChapter=chapterOf;window.setupAetheriaRankingHierarchy=hierarchy;
window.renderRank=function(){premium();status();hierarchy();const grid=document.querySelector('#rankingGrid'),info=document.querySelector('#rankInfo'),desc=document.querySelector('#rankDescription');if(!grid)return;const stage=(stageData?.stages||[]).find(s=>s.id===(window.__aetheriaSelectedStage||document.querySelector('#rankExactStageSelect')?.value)),n=limit();if(!stage){grid.innerHTML='<div class="empty"><b>Chọn chương và ải/chủ đề.</b><br>Aetheria không tự tạo bảng khi chưa có chặng xác minh.</div>';if(info)info.textContent='Chưa chọn chặng';return}if(!ready(stage)){grid.innerHTML=`<div class="empty"><b>Top ${n} chưa mở cho ${esc(stage.label||stage.name||stage.id)}.</b><br>Kho item vẫn giữ nguyên. Bảng điểm thật đang khóa vì thiếu internal item và/hoặc hệ số phán định, đối thủ, kỹ năng, tag cần thiết.<br><strong>Không dùng phép cộng 10 thuộc tính để giả làm điểm trận đấu.</strong></div>`;if(info)info.textContent=`Kho ${items.length.toLocaleString('vi-VN')} item • Top ${n} chờ dữ liệu điểm thật`;if(desc)desc.textContent=`${stage.label||stage.name} — chỉ công bố xếp hạng khi đủ đầu vào game.`;return}grid.innerHTML='<div class="empty"><b>Đã đủ đầu vào tính điểm.</b><br>Bộ máy tính điểm thật đang được hoàn thiện; chưa phát hành điểm giả lập.</div>';if(info)info.textContent=`Top ${n} • đầu vào đã đủ`};
window.optimize=function(){const out=document.querySelector('#optimizerResult');if(!out)return;const stage=(stageData?.stages||[]).find(s=>s.id===(window.__aetheriaSelectedStage||document.querySelector('#rankExactStageSelect')?.value));out.innerHTML=stage&&!ready(stage)?`<b>${esc(stage.label||stage.name)}</b><br>Chưa đủ dữ liệu tính điểm chiến đấu thật. Kho item không bị xóa.`:'Chọn một chặng cụ thể để kiểm tra dữ liệu.'};
setTimeout(()=>{premium();status();window.renderRank()},80);
})();