/* Aetheria runtime recovery: fixes the early app.js null-element abort and mobile navigation. */
(function(){
  function closeMenu(){const menu=document.querySelector('#menuBtn'),nav=document.querySelector('#nav');if(!menu||!nav)return;nav.classList.remove('open');menu.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')}
  function bindMenu(){const menu=document.querySelector('#menuBtn'),nav=document.querySelector('#nav');if(!menu||!nav||menu.dataset.bound)return;menu.dataset.bound='1';menu.setAttribute('aria-controls','nav');menu.setAttribute('aria-expanded','false');menu.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const open=!nav.classList.contains('open');nav.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});nav.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu()});document.addEventListener('click',e=>{if(nav.classList.contains('open')&&!nav.contains(e.target)&&e.target!==menu)closeMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});window.addEventListener('resize',()=>{if(window.innerWidth>900)closeMenu()})}
  function bindLogin(){const login=document.querySelector('#loginBtn'),dialog=document.querySelector('#loginDialog');if(login&&dialog&&!login.dataset.bound){login.dataset.bound='1';login.addEventListener('click',()=>typeof dialog.showModal==='function'?dialog.showModal():dialog.setAttribute('open',''))}}
  function bindLateAppHandlers(){if(typeof window.optimize==='function'){const btn=document.querySelector('#optimizeBtn');if(btn&&!btn.dataset.bound){btn.dataset.bound='1';btn.addEventListener('click',window.optimize)}document.querySelectorAll('#stageTabs button').forEach(b=>{if(b.dataset.recoveryBound)return;b.dataset.recoveryBound='1';b.addEventListener('click',()=>{document.querySelectorAll('#stageTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');window.optimize()})})}}
  async function start(){bindMenu();bindLogin();bindLateAppHandlers();if(typeof window.boot==='function'&&!window.__aetheriaBootRecovered){window.__aetheriaBootRecovered=true;try{await window.boot()}catch(err){console.error('Aetheria recovery boot failed',err);const h=document.querySelector('#heroStatus');if(h)h.innerHTML='<div>⚠ Có lỗi khi khởi tạo giao diện</div><small>Hãy tải lại trang nếu lỗi vẫn còn.</small>'}}bindMenu();bindLogin();bindLateAppHandlers()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
